# NumPy Superpowers: Broadcasting, Views, and Ufuncs

Before diving into neural networks, let's get familiar with NumPy, a foundational package for numerical operations in Python. This notebook will guide you through the intricacies of broadcasting, views, and universal functions (ufuncs) in NumPy.

## Table of Contents

1. Introduction to Broadcasting
2. Dive into Views
3. Universal Functions (Ufuncs)
4. Challenges and Puzzles


In [2]:
import numpy as np

## 1. Introduction to Broadcasting

Broadcasting allows NumPy to work with arrays of different shapes when performing arithmetic operations.

### 1.1 Basic Broadcasting

Broadcasting happens when you add a scalar to a matrix.

In [3]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = matrix + 1
print(result)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]



Here, the scalar 1 is broadcasted to the shape of the matrix, and then addition is performed element-wise.

**Exercise**: Given a 1D array `a` of shape `(3,)` and a 2D array `b` of shape `(3,3)`, add them together. What do you observe? Where does broadcasting play a role?


In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [4, 5, 6]])

print(a.shape)
print(b.shape)

(2, 3)
(4, 3)


In [5]:
a + b

ValueError: operands could not be broadcast together with shapes (2,3) (4,3) 

**Answer**: The 1D array `a` is broadcasted across the rows of `b` to match its shape, and then element-wise addition is performed.

### 1.2 Broadcasting Rules

**Question**: Can you multiply a 2D array of shape (2, 3) with another 2D array of shape (2, 2)? Why or why not?

**Answer**: No, you can't. The dimensions are not compatible according to the broadcasting rules.

For broadcasting to work, the dimensions of the arrays should be compatible. Dimensions are compatible when:


1.   They are equal, or
2.   One of them is 1.

# 2. Dive into Views

In NumPy, data is not always copied when creating new arrays or when reshaping. This is crucial for memory efficiency. A view is simply another way of accessing the data of the original array.

### 2.1 Basic Views

**Exercise**: Create a 2D array and obtain a view of its second row. Modify an element in the view. What happens to the original array?

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
view = arr[1]
# view
view[0] = 40
print(arr)

[[ 1  2  3]
 [40  5  6]
 [ 7  8  9]]


**Answer**: Modifying the view also modifies the original array. The value at arr[1, 0] changes to 40. (When you slice an array, you're creating a view, not a copy. This means that if you modify the view, the original array is modified as well.)

###2.2 Reshaping and Views

**Exercise**: Reshape a 1D array into a 2D array. Is the result a view or a copy? How can you confirm this?

In [9]:
arr_1d = np.array([1, 2, 3, 4])
arr_2d = arr_1d.reshape(2, 2)
arr_2d[0, 0] = 10
print(arr_1d)

[10  2  3  4]


**Answer**:  The reshaped array arr_2d is a view of arr_1d. Modifying arr_2d also modifies arr_1d. (Reshaping an array often returns a view, not a copy. This means changes in the reshaped array might reflect in the original array.)

# 3. Universal Functions (Ufuncs)

Ufuncs are functions that operate element-wise on one or more arrays. Most likely you use them all the time, even if you don't know what they are. They are a cornerstone of NumPy, allowing for efficient operations. A ufunc is a “vectorized” wrapper for a function that takes a fixed number of specific inputs and produces a fixed number of specific outputs


## A list of common Ufuncs:

*Mathematical Operations:*

    np.add(x1, x2): Add arguments element-wise.
    np.subtract(x1, x2): Subtract arguments element-wise.
    np.multiply(x1, x2): Multiply arguments element-wise.
    np.divide(x1, x2): Returns a true division of the inputs, element-wise.
    np.floor_divide(x1, x2): Return the largest integer smaller or equal to the division of the inputs.
    np.power(x1, x2): First array elements raised to powers from the second array, element-wise.
    np.mod(x1, x2): Return the element-wise remainder of division.
    np.square(x): Return the element-wise square of the input.
    np.absolute(x) or np.abs(x): Calculate the absolute value element-wise.
    np.sqrt(x): Return the non-negative square-root of an array, element-wise.

*Trigonometric Functions:*

    np.sin(x): Trigonometric sine, element-wise.
    np.cos(x): Cosine element-wise.
    np.tan(x): Compute tangent element-wise.
    np.arcsin(x): Inverse sine, element-wise.
    np.arccos(x): Trigonometric inverse cosine, element-wise.
    np.arctan(x): Trigonometric inverse tangent, element-wise.

*Hyperbolic Functions*:
    np.sinh(x): Hyperbolic sine, element-wise.
    np.cosh(x): Hyperbolic cosine, element-wise.
    np.tanh(x): Compute hyperbolic tangent element-wise.

*Comparison Functions*:

    np.greater(x1, x2): Return the truth value of (x1 > x2) element-wise.
    np.less(x1, x2): Return the truth value of (x1 < x2) element-wise.
    np.equal(x1, x2): Return (x1 == x2) element-wise.
    np.not_equal(x1, x2): Return (x1 != x2) element-wise.

*Exponential and Logarithmic Functions*:

    np.exp(x): Calculate the exponential of all elements in the input array.
    np.log(x): Natural logarithm, element-wise.
    np.log2(x): Base-2 logarithm of x.
    np.log10(x): Return the base 10 logarithm of the input array, element-wise.

*Rounding*:

    np.around(a, decimals=0): Evenly round to the given number of decimals.
    np.floor(x): Return the floor of the input, element-wise.
    np.ceil(x): Return the ceiling of the input, element-wise.

*Miscellaneous*:

    np.sign(x): Returns an element-wise indication of the sign of a number.

###3.1 Basic Ufuncs

**Exercise**: Use a ufunc to compute the square of each element in an array.


In [ ]:
arr = np.array([1, 2, 3, 4])
squared = np.square(arr)
print(squared)

### 3.2 Ufunc Broadcasting

Ufuncs also support broadcasting. This means you can combine arrays of different shapes in element-wise operations.

**Exercise**: Given two arrays of shapes (3, 3) and (3,), use a ufunc to subtract the second array from the first along the second axis.


In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([1, 2, 3])

result = arr1 - arr2
print(result)

[[0 0 0]
 [3 3 3]
 [6 6 6]]


###3.4 Advanced Ufuncs

Ufuncs have methods that allow for more advanced operations, like reducing an array along a particular axis.

**Exercise**: Use the reduce method of a ufunc to compute the product of all elements in an array.

In [ ]:
arr = np.array([1, 2, 3, 4])
product = np.multiply.reduce(arr)
print(product)

24
